services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - WEBAPP_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: unless-stopped
    environment: 
      PMA_HOST: mysql
      PMA_USER: WEBAPP_user
      PMA_PASSWORD: WEBAPP_password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - WEBAPP_network

volumes:
  mysql_data:

networks:
  WEBAPP_network:
